#!/usr/bin/env node

/**
 * Module dependencies.
 */
var program = require('commander');
var fs = require('fs');
var file = process.argv[2];
var newFile = process.argv[3];
var options = { encoding: 'utf8' };
var path = require('path');
var lib = require('./index');


program
  .version('0.0.1')
  .option('')
  .parse(process.argv);

var newFunction = function() {
	fs.readFile(file, options, function (err, contents) {
	fs.writeFile(newFile, contents, options, function (err) {
	if (err) throw err;
  	console.log('It\'s saved!');
  	});
});
};

var mP = __dirname;
console.log(mP);
var tempPath = path.join(mP, 'test/fixtures/source/layouts/default.html');
var pagePath = path.join(mP, 'test/fixtures/source/pages');
// var writePath = path.join(mP, 'test/fixtures/generated/new.txt');
lib.sourceTemplate(tempPath, function(temp) {
	lib.sourcePage(pagePath, function(pages) {
		pages.forEach(function(eachPage) {
			lib.fileReader(path.join(pagePath, eachPage), function(err, contents) {
				var resultArray = temp[0].concat(contents, temp[1]);
				console.log(resultArray);
				var writePath = path.join(mP, 'test/fixtures/generated', eachPage);
				lib.fileWriter(writePath, resultArray);
			});
		});

	});
});




lib.fileShreader(function(){});


